// Curated, professionally-composed theme presets. The AI picks the best-fit
// preset id for a studio rather than generating raw colors — this keeps
// visual quality guaranteed while still feeling "AI chosen" per studio.
export const THEME_PRESETS = [
    {
        id: "amber-noir",
        name: "Amber Noir",
        mood: "moody, upscale, dramatic — great for wedding & fine-art photography studios",
        bg: "#0b0a08",
        surface: "rgba(255,255,255,0.04)",
        primary: "#f59e0b",
        accent: "#d97706",
        text: "#fafafa",
        textMuted: "#a1a1aa",
        fontHeading: "'Playfair Display', Georgia, serif",
        fontBody: "'Inter', system-ui, sans-serif",
    },
    {
        id: "blush-editorial",
        name: "Blush Editorial",
        mood: "soft, romantic, airy — great for bridal, maternity and family portrait studios",
        bg: "#fdf6f3",
        surface: "#ffffff",
        primary: "#c2617a",
        accent: "#9c4a5f",
        text: "#2b1f22",
        textMuted: "#7a6569",
        fontHeading: "'Playfair Display', Georgia, serif",
        fontBody: "'Inter', system-ui, sans-serif",
    },
    {
        id: "midnight-cinema",
        name: "Midnight Cinema",
        mood: "sleek, cinematic, high-tech — great for videography and commercial/product studios",
        bg: "#05070d",
        surface: "rgba(255,255,255,0.05)",
        primary: "#38bdf8",
        accent: "#0ea5e9",
        text: "#f1f5f9",
        textMuted: "#94a3b8",
        fontHeading: "'Space Grotesk', 'Inter', sans-serif",
        fontBody: "'Inter', system-ui, sans-serif",
    },
    {
        id: "sage-minimal",
        name: "Sage Minimal",
        mood: "clean, calm, minimal — great for lifestyle, newborn and everyday portrait studios",
        bg: "#f7f8f5",
        surface: "#ffffff",
        primary: "#5c7a5e",
        accent: "#3f5940",
        text: "#232823",
        textMuted: "#697169",
        fontHeading: "'Cormorant Garamond', Georgia, serif",
        fontBody: "'Inter', system-ui, sans-serif",
    },
    {
        id: "sunset-warm",
        name: "Sunset Warm",
        mood: "vibrant, energetic, joyful — great for lifestyle, event and travel photography studios",
        bg: "#1a0f0a",
        surface: "rgba(255,255,255,0.05)",
        primary: "#fb7185",
        accent: "#f97316",
        text: "#fff7ed",
        textMuted: "#d6b8a8",
        fontHeading: "'Playfair Display', Georgia, serif",
        fontBody: "'Inter', system-ui, sans-serif",
    },
    {
        id: "mono-classic",
        name: "Mono Classic",
        mood: "bold, high-contrast, gallery-like — great for fine-art, editorial and fashion studios",
        bg: "#0a0a0a",
        surface: "rgba(255,255,255,0.04)",
        primary: "#ffffff",
        accent: "#a3a3a3",
        text: "#fafafa",
        textMuted: "#a3a3a3",
        fontHeading: "'Playfair Display', Georgia, serif",
        fontBody: "'Inter', system-ui, sans-serif",
    },
];

export const getTheme = (id) => THEME_PRESETS.find((t) => t.id === id) || THEME_PRESETS[0];
